import type { Asset } from '@bot-avatar/core';
export const assets = [
  {
    id: 'hair-hime-cut',
    source: 'assets/parts/soft-layered-2d/hair/hime-cut.svg',
    creator: 'Bot Avatar project; sculpted hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-hime-cut-back',
    source: 'assets/parts/soft-layered-2d/hair/hime-cut-back.svg',
    creator: 'Bot Avatar project; sculpted hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-sculpted-waves',
    source: 'assets/parts/soft-layered-2d/hair/sculpted-waves.svg',
    creator: 'Bot Avatar project; sculpted hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-sculpted-waves-back',
    source: 'assets/parts/soft-layered-2d/hair/sculpted-waves-back.svg',
    creator: 'Bot Avatar project; sculpted hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-wolf-cut',
    source: 'assets/parts/soft-layered-2d/hair/wolf-cut.svg',
    creator: 'Bot Avatar project; layered hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-wolf-cut-back',
    source: 'assets/parts/soft-layered-2d/hair/wolf-cut-back.svg',
    creator: 'Bot Avatar project; layered hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-feather-flip',
    source: 'assets/parts/soft-layered-2d/hair/feather-flip.svg',
    creator: 'Bot Avatar project; layered hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-feather-flip-back',
    source: 'assets/parts/soft-layered-2d/hair/feather-flip-back.svg',
    creator: 'Bot Avatar project; layered hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-rounded-bob',
    source: 'assets/parts/soft-layered-2d/hair/rounded-bob.svg',
    creator: 'Bot Avatar project; rounded bob exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-rounded-bob-back',
    source: 'assets/parts/soft-layered-2d/hair/rounded-bob-back.svg',
    creator: 'Bot Avatar project; rounded bob exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-layered-fringe',
    source: 'assets/parts/soft-layered-2d/hair/layered-fringe.svg',
    creator: 'Bot Avatar project; layered fringe exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-wispy-fringe',
    source: 'assets/parts/soft-layered-2d/hair/wispy-fringe.svg',
    creator: 'Bot Avatar project; layered fringe exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-curtain',
    source: 'assets/parts/soft-layered-2d/hair/curtain.svg',
    creator: 'Bot Avatar project; Soft Layered 2D hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-soft-curls',
    source: 'assets/parts/soft-layered-2d/hair/soft-curls.svg',
    creator: 'Bot Avatar project; Soft Layered 2D hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-soft-curls-back',
    source: 'assets/parts/soft-layered-2d/hair/soft-curls-back.svg',
    creator: 'Bot Avatar project; Soft Layered 2D hair exploration',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hat-pilot-strap',
    source: 'assets/parts/soft-layered-2d/hats/pilot-strap.svg',
    creator: 'Bot Avatar project; layered aviator accessory',
    permission: 'project-owned',
    anchor: [128, 106],
  },
  {
    id: 'hat-pilot-frame',
    source: 'assets/parts/soft-layered-2d/hats/pilot-frame.svg',
    creator: 'Bot Avatar project; layered aviator accessory',
    permission: 'project-owned',
    anchor: [128, 106],
  },
  {
    id: 'hat-pilot-lenses',
    source: 'assets/parts/soft-layered-2d/hats/pilot-lenses.svg',
    creator: 'Bot Avatar project; layered aviator accessory',
    permission: 'project-owned',
    anchor: [128, 106],
  },
  {
    id: 'hair-sweep-bucket-back',
    source: 'assets/parts/soft-layered-2d/hair/sweep-bucket-back.svg',
    creator: 'Bot Avatar project; bucket-hat fit from user-provided close-up',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-sweep-bucket',
    source: 'assets/parts/soft-layered-2d/hair/sweep-bucket.svg',
    creator: 'Bot Avatar project; bucket-hat fit from user-provided close-up',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'face-round',
    source: 'assets/parts/soft-layered-2d/faces/round.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-sweep',
    source: 'assets/parts/soft-layered-2d/hair/sweep.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-sweep-back',
    source: 'assets/parts/soft-layered-2d/hair/sweep-back.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-crop-back',
    source: 'assets/parts/soft-layered-2d/hair/crop-back.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hat-cap',
    source: 'assets/parts/soft-layered-2d/hats/cap.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-cap-backward',
    source: 'assets/parts/soft-layered-2d/hats/cap-backward.svg',
    creator: 'Bot Avatar project; frontal backward cap inspired by user-provided hat reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-beanie',
    source: 'assets/parts/soft-layered-2d/hats/beanie.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-beret',
    source: 'assets/parts/soft-layered-2d/hats/beret.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-hardhat',
    source: 'assets/parts/soft-layered-2d/hats/hardhat.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-bucket',
    source: 'assets/parts/soft-layered-2d/hats/bucket.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-deerstalker',
    source: 'assets/parts/soft-layered-2d/hats/deerstalker.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hair-wave',
    source: 'assets/parts/soft-layered-2d/hair/wave.svg',
    creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'hair-side-part',
    source: 'assets/parts/soft-layered-2d/hair/side-part.svg',
    creator: 'Bot Avatar project; side-part hairstyle for the Soft Layered 2D profile',
    permission: 'project-owned',
    anchor: [128, 128],
  },
  {
    id: 'badge-code',
    source: 'assets/icons/lucide/code-xml.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/code-xml.svg',
      sha256: '9f3b21989a68d727da9a152e08483fa55f9048d476d3a4c94e94b8b88d25c2a8',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-sparkle',
    source: 'assets/icons/lucide/sparkles.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/sparkles.svg',
      sha256: '80e2cf4afe55a0544a300dda60540ac195c5c308ee84f231f9fafc67bdb38c8b',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-document',
    source: 'assets/icons/lucide/file-text.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/file-text.svg',
      sha256: '56582e205bca1dc510113d529ea45e5ff83fc19761cafd23b94f72f3b3b83844',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-git',
    source: 'assets/icons/lucide/git-branch.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/git-branch.svg',
      sha256: '3d24297cbf0bc75670573449a44f4d9ab0349d6188674d746db44b1f46c3256f',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-check',
    source: 'assets/icons/lucide/circle-check.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/circle-check.svg',
      sha256: '201e790f3a05c65b2c4b0f952c9b9e1f35cd1c5b21698b3f4be131883fe90bc8',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-terminal',
    source: 'assets/icons/lucide/terminal.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/terminal.svg',
      sha256: 'bebe46d638f87696d513f5d4a0f46806470ba45187bc915b9081846f1446a212',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-gear',
    source: 'assets/icons/lucide/settings.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/settings.svg',
      sha256: 'e1a4b3d021b2063bf8a76f95ba9abeebbce08d0872e358a46eb1dc4e8cb911a0',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-bug',
    source: 'assets/icons/lucide/bug.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/bug.svg',
      sha256: 'c40cca1d4eb02ae15108099bf98e986e63480f23e7a837a7e564cd7a16e414aa',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-printer',
    source: 'assets/icons/lucide/printer.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/printer.svg',
      sha256: 'f8f15151f722f614d5e1e4b7b6af7f3ce87e63a637f6a8291bb4fb9b8f5dfd61',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-wifi',
    source: 'assets/icons/lucide/wifi.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/wifi.svg',
      sha256: '746f5598ee25a3023f91fc71789203309bb481504d23c7b0bb3e8e4577c4645c',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-general',
    source: 'assets/icons/lucide/message-circle-more.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/message-circle-more.svg',
      sha256: 'c995d95d73e6186da6d8e376129bc1682388e89b32c5a25e18e36b09cba6f9b8',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-flask',
    source: 'assets/icons/lucide/flask-conical.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/flask-conical.svg',
      sha256: '20cf3f0295cabd0fc7fac07264d3093d338b5297bcacfce4681e4a71c291a9cc',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-rocket',
    source: 'assets/icons/lucide/rocket.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/rocket.svg',
      sha256: '14797c38eed21fe914bf2cf36bcf456883112e5dd37a0a3a2b402e68e7db8f4d',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-pulse',
    source: 'assets/icons/lucide/activity.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/activity.svg',
      sha256: '604b8d691ce01131195ebf8d6a5b0ba877f94dd3fd71d3cddce7d5a2ec3ad0f3',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-shield',
    source: 'assets/icons/lucide/shield-lock.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/shield-lock.svg',
      sha256: 'fa9b8803c7a6aa1881e898bbbc097ac4b2f6e7cb44579b4240cf2bdfa769bd84',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-pen',
    source: 'assets/icons/lucide/pen-tool.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/pen-tool.svg',
      sha256: 'c0f2491ac4f416cbc69ae088045a23f355ee87e2130ec61325a34b6330639557',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-bars',
    source: 'assets/icons/lucide/chart-no-axes-column-increasing.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/chart-no-axes-column-increasing.svg',
      sha256: 'edb83a39087c0247adbf4a0140f11fb75b7b3c5898ecb0f8da04275dadfa1215',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-search',
    source: 'assets/icons/lucide/search.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/search.svg',
      sha256: 'fb56eee57ec4d05d29f1925503c911448f9837c6849a2cdbe66920fa25e923a8',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'badge-support',
    source: 'assets/icons/lucide/message-circle-heart.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/message-circle-heart.svg',
      sha256: 'd987ca5114a6dcb087c2828fe23c0745add91c7fa0fa1d4599e79c787e97ffc2',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'icon-dot',
    source: 'assets/icons/lucide/dot.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/dot.svg',
      sha256: '59a9177639bb7f251635cf4e491b626a6ebf8b2f922c5a4e4208ea5afcb2f03c',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'icon-check',
    source: 'assets/icons/lucide/check.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/check.svg',
      sha256: 'ff17520d560da21c41dc6d876bd45ec1f04903ccc0283339ff20f4e45adf6328',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'icon-server',
    source: 'assets/icons/lucide/server.svg',
    creator: 'Lucide Icons and Contributors',
    permission: 'ISC',
    anchor: [128, 128],
    upstream: {
      package: 'lucide-static',
      version: '1.49.0',
      url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/server.svg',
      sha256: 'a54134ddb234e6e8af218144a9659cabcadefc5a33ed861cac5ef6b92aa024b1',
      licensePath: 'assets/icons/lucide/LICENSE',
    },
  },
  {
    id: 'hat-flatcap',
    source: 'assets/parts/soft-layered-2d/hats/flatcap.svg',
    creator: 'Bot Avatar project; occupational Fine Line collection',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-patrol',
    source: 'assets/parts/soft-layered-2d/hats/patrol.svg',
    creator: 'Bot Avatar project; occupational Fine Line collection',
    permission: 'project-owned',
    anchor: [128, 64],
  },
  {
    id: 'hat-pilot',
    source: 'assets/parts/soft-layered-2d/hats/pilot.svg',
    creator: 'Bot Avatar project; occupational Fine Line collection',
    permission: 'project-owned',
    anchor: [128, 64],
  },
] as const satisfies readonly Asset[];
