import type { Catalog } from '@bot-avatar/core';
import { assets } from './assets.js';
import { templates } from './templates.js';
import { softLayered2dHair } from './hair.js';
export const catalog = {
  version: '1.19.6',
  styleId: 'soft-layered-2d',
  assets,
  colors: {
    cocoa: '#654638',
    plum: '#61435f',
    copper: '#975634',
    silver: '#c4ced7',
    purple: '#b961f5',
    mint: '#b1daad',
    'mint-hair': '#a1cd9c',
    'mint-ring': '#84b87b',
    amber: '#f4ca76',
    pink: '#ed99c1',
    blue: '#7999ef',
    charcoal: '#525258',
    navy: '#334b70',
    teal: '#278b88',
    coral: '#f68178',
    skin: '#faf5ee',
    ink: '#171918',
    white: '#ffffff',
    cream: '#f6f3ee',
    slate: '#687d8b',
    sky: '#c7e5ee',
    cyan: '#87d8e2',
    yellow: '#ffd16e',
    salmon: '#fc847b',
    'review-green': '#a6d9b0',
    'build-blue': '#80c6f5',
    'safety-yellow': '#f5c542',
    'safety-red': '#cc4545',
    'field-olive': '#747b49',
    'tweed-taupe': '#a68b70',
    'aviator-leather': '#92603f',
    'uniform-blue': '#3569a5',
    'debug-pink': '#f98eaa',
    orange: '#ffad5a',
    'network-blue': '#589afa',
    'ai-pink': '#edb0df',
    ivory: '#dedbd2',
    lime: '#c2e783',
    aqua: '#82d0ca',
    'monitor-blue': '#526cac',
    'design-salmon': '#ffa795',
    'data-cyan': '#72d4e3',
    sand: '#ebd099',
    'support-green': '#9fd38b',
    'emblem-ivory': '#f8f5ed',
  },
  hair: softLayered2dHair,
  hairBack: {
    'hair-sweep': 'hair-sweep-back',
    'hair-wave': 'hair-crop-back',
    'hair-side-part': 'hair-crop-back',
    'hair-curtain': 'hair-crop-back',
    'hair-soft-curls': 'hair-soft-curls-back',
    'hair-layered-fringe': 'hair-crop-back',
    'hair-wispy-fringe': 'hair-crop-back',
    'hair-rounded-bob': 'hair-rounded-bob-back',
    'hair-wolf-cut': 'hair-wolf-cut-back',
    'hair-feather-flip': 'hair-feather-flip-back',
    'hair-hime-cut': 'hair-hime-cut-back',
    'hair-sculpted-waves': 'hair-sculpted-waves-back',
  },
  faces: ['face-round'],
  glasses: ['none'],
  instanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
  defaults: {
    hairColor: 'purple',
    iconColor: 'ink',
    face: 'face-round',
    glasses: 'none',
    background: 'slate',
    gradientEnd: 'sky',
  },
  roles: {
    coder: 'coder',
    research: 'research',
    docs: 'docs',
    git: 'git',
    review: 'review',
    shell: 'shell',
    build: 'build',
    debug: 'debug',
    printer: 'printer',
    network: 'network',
    ai: 'ai',
    general: 'general',
    test: 'test',
    deploy: 'deploy',
    monitor: 'monitor',
    security: 'security',
    design: 'design',
    data: 'data',
    search: 'search',
    support: 'support',
    // Legacy request ids. They are not templates; normalization selects the role default.
    assistant: 'coder',
    builder: 'test',
    caretaker: 'security',
  },
  templates,
  instanceBadgeAssets: {
    dot: 'icon-dot',
    check: 'icon-check',
    terminal: 'badge-terminal',
    search: 'badge-search',
    server: 'icon-server',
  },
} as const satisfies Catalog;
