import type { Catalog } from '@bot-avatar/core';
const flat2dHair = ['hair-sweep', 'hair-wave', 'hair-side-part'] as const;
export const catalog = {
  version: '1.12.0',
  styleId: 'flat-2d',
  assets: [
    {
      id: 'hat-pilot-strap',
      source: 'assets/parts/flat-2d/hats/pilot-strap.svg',
      creator: 'Bot Avatar project; layered aviator accessory',
      permission: 'project-owned',
      anchor: [128, 106],
    },
    {
      id: 'hat-pilot-frame',
      source: 'assets/parts/flat-2d/hats/pilot-frame.svg',
      creator: 'Bot Avatar project; layered aviator accessory',
      permission: 'project-owned',
      anchor: [128, 106],
    },
    {
      id: 'hat-pilot-lenses',
      source: 'assets/parts/flat-2d/hats/pilot-lenses.svg',
      creator: 'Bot Avatar project; layered aviator accessory',
      permission: 'project-owned',
      anchor: [128, 106],
    },
    {
      id: 'hair-sweep-bucket-back',
      source: 'assets/parts/flat-2d/hair/sweep-bucket-back.svg',
      creator: 'Bot Avatar project; bucket-hat fit from user-provided close-up',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hair-sweep-bucket',
      source: 'assets/parts/flat-2d/hair/sweep-bucket.svg',
      creator: 'Bot Avatar project; bucket-hat fit from user-provided close-up',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'face-round',
      source: 'assets/parts/flat-2d/faces/round.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hair-sweep',
      source: 'assets/parts/flat-2d/hair/sweep.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hair-sweep-back',
      source: 'assets/parts/flat-2d/hair/sweep-back.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hair-crop-back',
      source: 'assets/parts/flat-2d/hair/crop-back.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided v0.3 visual direction',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hat-cap',
      source: 'assets/parts/flat-2d/hats/cap.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-beanie',
      source: 'assets/parts/flat-2d/hats/beanie.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-beret',
      source: 'assets/parts/flat-2d/hats/beret.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-hardhat',
      source: 'assets/parts/flat-2d/hats/hardhat.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-bucket',
      source: 'assets/parts/flat-2d/hats/bucket.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-deerstalker',
      source: 'assets/parts/flat-2d/hats/deerstalker.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hair-wave',
      source: 'assets/parts/flat-2d/hair/wave.svg',
      creator: 'Bot Avatar project; SVG redrawn from user-provided hat diversity reference',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'hair-side-part',
      source: 'assets/parts/flat-2d/hair/side-part.svg',
      creator: 'Bot Avatar project; side-part hairstyle for the Soft Layered 2D profile',
      permission: 'project-owned',
      anchor: [128, 128],
    },
    {
      id: 'badge-code',
      source: 'assets/icons/lucide/code-xml.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/code-xml.svg',
        sha256: '9f3b21989a68d727da9a152e08483fa55f9048d476d3a4c94e94b8b88d25c2a8',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-sparkle',
      source: 'assets/icons/lucide/sparkles.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/sparkles.svg',
        sha256: '80e2cf4afe55a0544a300dda60540ac195c5c308ee84f231f9fafc67bdb38c8b',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-document',
      source: 'assets/icons/lucide/file-text.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/file-text.svg',
        sha256: '56582e205bca1dc510113d529ea45e5ff83fc19761cafd23b94f72f3b3b83844',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-git',
      source: 'assets/icons/lucide/git-branch.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/git-branch.svg',
        sha256: '3d24297cbf0bc75670573449a44f4d9ab0349d6188674d746db44b1f46c3256f',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-check',
      source: 'assets/icons/lucide/circle-check.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/circle-check.svg',
        sha256: '201e790f3a05c65b2c4b0f952c9b9e1f35cd1c5b21698b3f4be131883fe90bc8',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-terminal',
      source: 'assets/icons/lucide/terminal.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/terminal.svg',
        sha256: 'bebe46d638f87696d513f5d4a0f46806470ba45187bc915b9081846f1446a212',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-gear',
      source: 'assets/icons/lucide/settings.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/settings.svg',
        sha256: 'e1a4b3d021b2063bf8a76f95ba9abeebbce08d0872e358a46eb1dc4e8cb911a0',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-bug',
      source: 'assets/icons/lucide/bug.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/bug.svg',
        sha256: 'c40cca1d4eb02ae15108099bf98e986e63480f23e7a837a7e564cd7a16e414aa',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-printer',
      source: 'assets/icons/lucide/printer.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/printer.svg',
        sha256: 'f8f15151f722f614d5e1e4b7b6af7f3ce87e63a637f6a8291bb4fb9b8f5dfd61',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-wifi',
      source: 'assets/icons/lucide/wifi.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/wifi.svg',
        sha256: '746f5598ee25a3023f91fc71789203309bb481504d23c7b0bb3e8e4577c4645c',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-general',
      source: 'assets/icons/lucide/message-circle-more.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/message-circle-more.svg',
        sha256: 'c995d95d73e6186da6d8e376129bc1682388e89b32c5a25e18e36b09cba6f9b8',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-flask',
      source: 'assets/icons/lucide/flask-conical.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/flask-conical.svg',
        sha256: '20cf3f0295cabd0fc7fac07264d3093d338b5297bcacfce4681e4a71c291a9cc',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-rocket',
      source: 'assets/icons/lucide/rocket.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/rocket.svg',
        sha256: '14797c38eed21fe914bf2cf36bcf456883112e5dd37a0a3a2b402e68e7db8f4d',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-pulse',
      source: 'assets/icons/lucide/activity.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/activity.svg',
        sha256: '604b8d691ce01131195ebf8d6a5b0ba877f94dd3fd71d3cddce7d5a2ec3ad0f3',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-shield',
      source: 'assets/icons/lucide/shield-lock.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/shield-lock.svg',
        sha256: 'fa9b8803c7a6aa1881e898bbbc097ac4b2f6e7cb44579b4240cf2bdfa769bd84',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-pen',
      source: 'assets/icons/lucide/pen-tool.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/pen-tool.svg',
        sha256: 'c0f2491ac4f416cbc69ae088045a23f355ee87e2130ec61325a34b6330639557',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-bars',
      source: 'assets/icons/lucide/chart-no-axes-column-increasing.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/chart-no-axes-column-increasing.svg',
        sha256: 'edb83a39087c0247adbf4a0140f11fb75b7b3c5898ecb0f8da04275dadfa1215',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-search',
      source: 'assets/icons/lucide/search.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/search.svg',
        sha256: 'fb56eee57ec4d05d29f1925503c911448f9837c6849a2cdbe66920fa25e923a8',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'badge-support',
      source: 'assets/icons/lucide/message-circle-heart.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/message-circle-heart.svg',
        sha256: 'd987ca5114a6dcb087c2828fe23c0745add91c7fa0fa1d4599e79c787e97ffc2',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'icon-dot',
      source: 'assets/icons/lucide/dot.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/dot.svg',
        sha256: '59a9177639bb7f251635cf4e491b626a6ebf8b2f922c5a4e4208ea5afcb2f03c',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'icon-check',
      source: 'assets/icons/lucide/check.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/check.svg',
        sha256: 'ff17520d560da21c41dc6d876bd45ec1f04903ccc0283339ff20f4e45adf6328',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'icon-server',
      source: 'assets/icons/lucide/server.svg',
      creator: 'Lucide Icons and Contributors',
      permission: 'ISC',
      anchor: [128, 128],
      upstream: {
        package: 'lucide-static',
        version: '1.49.0',
        url: 'https://cdn.jsdelivr.net/npm/lucide-static@1.49.0/icons/server.svg',
        sha256: 'a54134ddb234e6e8af218144a9659cabcadefc5a33ed861cac5ef6b92aa024b1',
        licensePath: 'assets/icons/lucide/LICENSE',
      },
    },
    {
      id: 'hat-flatcap',
      source: 'assets/parts/flat-2d/hats/flatcap.svg',
      creator: 'Bot Avatar project; occupational Fine Line collection',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-patrol',
      source: 'assets/parts/flat-2d/hats/patrol.svg',
      creator: 'Bot Avatar project; occupational Fine Line collection',
      permission: 'project-owned',
      anchor: [128, 64],
    },
    {
      id: 'hat-pilot',
      source: 'assets/parts/flat-2d/hats/pilot.svg',
      creator: 'Bot Avatar project; occupational Fine Line collection',
      permission: 'project-owned',
      anchor: [128, 64],
    },
  ],
  colors: {
    cocoa: '#654638',
    plum: '#61435f',
    copper: '#975634',
    silver: '#c4ced7',
    purple: '#b961f5',
    mint: '#b1daad',
    'mint-hair': '#a1cd9c',
    'mint-ring': '#84b87b',
    amber: '#f4ca76',
    pink: '#ed99c1',
    blue: '#7999ef',
    charcoal: '#525258',
    navy: '#334b70',
    teal: '#278b88',
    coral: '#f68178',
    skin: '#faf5ee',
    ink: '#171918',
    white: '#ffffff',
    cream: '#f6f3ee',
    slate: '#687d8b',
    sky: '#c7e5ee',
    cyan: '#87d8e2',
    yellow: '#ffd16e',
    salmon: '#fc847b',
    'review-green': '#a6d9b0',
    'build-blue': '#80c6f5',
    'safety-yellow': '#f5c542',
    'safety-red': '#cc4545',
    'field-olive': '#747b49',
    'tweed-taupe': '#a68b70',
    'aviator-leather': '#92603f',
    'uniform-blue': '#3569a5',
    'debug-pink': '#f98eaa',
    orange: '#ffad5a',
    'network-blue': '#589afa',
    'ai-pink': '#edb0df',
    ivory: '#dedbd2',
    lime: '#c2e783',
    aqua: '#82d0ca',
    'monitor-blue': '#526cac',
    'design-salmon': '#ffa795',
    'data-cyan': '#72d4e3',
    sand: '#ebd099',
    'support-green': '#9fd38b',
    'emblem-ivory': '#f8f5ed',
  },
  hair: flat2dHair,
  hairBack: {
    'hair-sweep': 'hair-sweep-back',
    'hair-wave': 'hair-crop-back',
    'hair-side-part': 'hair-crop-back',
  },
  faces: ['face-round'],
  glasses: ['none'],
  instanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
  defaults: {
    hairColor: 'purple',
    iconColor: 'ink',
    face: 'face-round',
    glasses: 'none',
    background: 'slate',
    gradientEnd: 'sky',
  },
  roles: {
    coder: 'coder',
    research: 'research',
    docs: 'docs',
    git: 'git',
    review: 'review',
    shell: 'shell',
    build: 'build',
    debug: 'debug',
    printer: 'printer',
    network: 'network',
    ai: 'ai',
    general: 'general',
    test: 'test',
    deploy: 'deploy',
    monitor: 'monitor',
    security: 'security',
    design: 'design',
    data: 'data',
    search: 'search',
    support: 'support',
    // Legacy request ids. They are not templates; normalization selects the role default.
    assistant: 'coder',
    builder: 'test',
    caretaker: 'security',
  },
  templates: [
    {
      id: 'coder',
      role: 'coder',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beanie',
        color: 'charcoal',
        badge: 'badge-code',
        badgeColor: 'cyan',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'cocoa',
      allowedHair: ['hair-sweep', 'hair-side-part', 'hair-wave'],
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'purple',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
      ],
    },
    {
      id: 'research',
      role: 'research',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beret',
        color: 'navy',
        badge: 'badge-sparkle',
        badgeColor: 'emblem-ivory',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'cyan',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'cyan',
        'silver',
        'sand',
        'mint',
        'coral',
        'copper',
        'teal',
        'pink',
        'blue',
        'amber',
        'purple',
      ],
    },
    {
      id: 'docs',
      role: 'docs',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'ivory',
        badge: 'badge-document',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'yellow',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'yellow',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'git',
      role: 'git',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'salmon',
        badge: 'badge-git',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'salmon',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'salmon',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'review',
      role: 'review',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'review-green',
        badge: 'badge-check',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'review-green',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'review-green',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'shell',
      role: 'shell',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beanie',
        color: 'charcoal',
        badge: 'badge-terminal',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'charcoal',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'charcoal',
        'silver',
        'sand',
        'mint',
        'coral',
        'copper',
        'teal',
        'pink',
        'blue',
        'amber',
        'purple',
      ],
    },
    {
      id: 'build',
      role: 'build',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-hardhat',
        color: 'safety-yellow',
        badge: 'badge-gear',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'build-blue',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'build-blue',
        'copper',
        'cocoa',
        'plum',
        'navy',
        'silver',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'debug',
      role: 'debug',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-bucket',
        color: 'field-olive',
        badge: 'badge-bug',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'debug-pink',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'debug-pink',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'printer',
      role: 'printer',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'charcoal',
        badge: 'badge-printer',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'orange',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'orange',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'network',
      role: 'network',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'uniform-blue',
        badge: 'badge-wifi',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'network-blue',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'network-blue',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'ai',
      role: 'ai',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beret',
        color: 'ai-pink',
        badge: 'badge-sparkle',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'ai-pink',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'ai-pink',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'general',
      role: 'general',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'ivory',
        badge: 'badge-general',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'ivory',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'ivory',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'test',
      role: 'test',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'lime',
        badge: 'badge-flask',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'lime',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'lime',
        'cocoa',
        'plum',
        'navy',
        'purple',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
      ],
    },
    {
      id: 'deploy',
      role: 'deploy',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'navy',
        badge: 'badge-rocket',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'aqua',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'aqua',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'monitor',
      role: 'monitor',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'monitor-blue',
        badge: 'badge-pulse',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'monitor-blue',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'monitor-blue',
        'silver',
        'sand',
        'mint',
        'coral',
        'copper',
        'teal',
        'pink',
        'blue',
        'amber',
        'purple',
      ],
    },
    {
      id: 'security',
      role: 'security',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'charcoal',
        badge: 'badge-shield',
        badgeColor: 'emblem-ivory',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'charcoal',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'charcoal',
        'silver',
        'sand',
        'mint',
        'coral',
        'copper',
        'teal',
        'pink',
        'blue',
        'amber',
        'purple',
      ],
    },
    {
      id: 'design',
      role: 'design',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beret',
        color: 'charcoal',
        badge: 'badge-pen',
        badgeColor: 'emblem-ivory',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'design-salmon',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'design-salmon',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'data',
      role: 'data',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-beanie',
        color: 'data-cyan',
        badge: 'badge-bars',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'data-cyan',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'data-cyan',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'search',
      role: 'search',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-deerstalker',
        color: 'sand',
        badge: 'badge-search',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'sand',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'sand',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'support',
      role: 'support',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-cap',
        color: 'support-green',
        badge: 'badge-support',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'support-green',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'support-green',
        'cocoa',
        'plum',
        'navy',
        'charcoal',
        'silver',
        'copper',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
    {
      id: 'docs-editor',
      role: 'docs',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-flatcap',
        color: 'tweed-taupe',
        badge: 'badge-document',
        badgeColor: 'ink',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'ivory',
      allowedHairColors: [
        'ivory',
        'cocoa',
        'plum',
        'silver',
        'teal',
        'copper',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    },
    {
      id: 'security-officer',
      role: 'security',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-patrol',
        color: 'navy',
        badge: 'badge-shield',
        badgeColor: 'yellow',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'navy',
      allowedHairColors: [
        'navy',
        'cocoa',
        'plum',
        'silver',
        'teal',
        'copper',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    },
    {
      id: 'deploy-aviator',
      role: 'deploy',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-pilot',
        color: 'aviator-leather',
        badge: 'badge-rocket',
        badgeColor: 'emblem-ivory',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'orange',
      allowedHairColors: [
        'orange',
        'cocoa',
        'plum',
        'silver',
        'teal',
        'copper',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    },
    {
      id: 'build-red',
      role: 'build',
      styleId: 'flat-2d',
      hat: {
        type: 'hat-hardhat',
        color: 'safety-red',
        badge: 'badge-gear',
        badgeColor: 'white',
      },
      defaultPalette: 'skin',
      defaultHairColor: 'build-blue',
      allowedHair: flat2dHair,
      allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
      allowedHairColors: [
        'build-blue',
        'copper',
        'cocoa',
        'plum',
        'navy',
        'silver',
        'teal',
        'pink',
        'mint',
        'blue',
        'amber',
        'coral',
        'purple',
      ],
    },
  ],
  instanceBadgeAssets: {
    dot: 'icon-dot',
    check: 'icon-check',
    terminal: 'badge-terminal',
    search: 'badge-search',
    server: 'icon-server',
  },
} as const satisfies Catalog;
export const flat2dHatMounts = {
  'hat-cap': {
    x: 128,
    y: 66,
    scale: 0.84,
    rotation: 0,
  },
  'hat-beanie': {
    x: 151,
    y: 87,
    scale: 0.86,
    rotation: 3,
  },
  'hat-beret': {
    x: 176,
    y: 65,
    scale: 0.85,
    rotation: 12,
  },
  'hat-hardhat': {
    x: 128,
    y: 77,
    scale: 0.82,
    rotation: 0,
  },
  'hat-bucket': {
    x: 128,
    y: 67,
    scale: 0.85,
    rotation: 0,
  },
  'hat-deerstalker': {
    x: 128,
    y: 68,
    scale: 0.83,
    rotation: 0,
  },
  'hat-flatcap': {
    x: 130,
    y: 71,
    scale: 0.74,
    rotation: -8,
  },
  'hat-patrol': {
    x: 128,
    y: 68,
    scale: 0.79,
    rotation: 0,
  },
  'hat-pilot': {
    x: 128,
    y: 64,
    scale: 0.85,
    rotation: 0,
  },
} as const;
export const flat2dBadgeTreatments = {
  'badge-code': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-sparkle': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-document': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-git': {
    backing: 'dark',
    size: 50,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-check': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-terminal': {
    backing: 'dark',
    size: 50,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-gear': {
    backing: 'none',
    size: 61,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-bug': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-printer': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-wifi': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-general': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-flask': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-rocket': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-pulse': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-shield': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-pen': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-bars': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-search': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
  'badge-support': {
    backing: 'none',
    size: 56,
    offsetX: 0,
    offsetY: 0,
  },
} as const;
export const flat2dHairFits: Readonly<
  Record<string, Readonly<Record<string, { readonly front: string; readonly back: string }>>>
> = {
  'hat-bucket': {
    'hair-sweep': {
      front: 'hair-sweep-bucket',
      back: 'hair-sweep-bucket-back',
    },
  },
};

// Accessories are fixed parts of the hat, not instance choices.
export const flat2dHatAccessories: Readonly<
  Record<
    string,
    readonly {
      readonly asset: string;
      readonly shadow: {
        readonly blur: number;
        readonly offset: number;
        readonly opacity: number;
      } | null;
    }[]
  >
> = {
  'hat-pilot': [
    { asset: 'hat-pilot-strap', shadow: { blur: 0.6, offset: 0.6, opacity: 0.1 } },
    { asset: 'hat-pilot-frame', shadow: { blur: 1.1, offset: 1.6, opacity: 0.2 } },
    { asset: 'hat-pilot-lenses', shadow: null },
  ],
};
