import type { BotTemplate } from '@bot-avatar/core';
import { softLayered2dHair } from './hair.js';
export const templates = [
  {
    id: 'coder',
    role: 'coder',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beanie',
      color: 'charcoal',
      badge: 'badge-code',
      badgeColor: 'cyan',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'cocoa',
    allowedHair: [
      'hair-sweep',
      'hair-curtain',
      'hair-rounded-bob',
      'hair-wave',
      'hair-soft-curls',
      'hair-layered-fringe',
      'hair-wispy-fringe',
      'hair-side-part',
      'hair-wolf-cut',
      'hair-feather-flip',
      'hair-hime-cut',
      'hair-sculpted-waves',
    ],
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'purple',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
    ],
  },
  {
    id: 'research',
    role: 'research',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beret',
      color: 'navy',
      badge: 'badge-sparkle',
      badgeColor: 'emblem-ivory',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'cyan',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'cyan',
      'silver',
      'sand',
      'mint',
      'coral',
      'copper',
      'teal',
      'pink',
      'blue',
      'amber',
      'purple',
    ],
  },
  {
    id: 'docs',
    role: 'docs',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'ivory',
      badge: 'badge-document',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'yellow',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'yellow',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'git',
    role: 'git',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'salmon',
      badge: 'badge-git',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'salmon',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'salmon',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'review',
    role: 'review',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'review-green',
      badge: 'badge-check',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'review-green',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'review-green',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'shell',
    role: 'shell',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beanie',
      color: 'charcoal',
      badge: 'badge-terminal',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'charcoal',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'charcoal',
      'silver',
      'sand',
      'mint',
      'coral',
      'copper',
      'teal',
      'pink',
      'blue',
      'amber',
      'purple',
    ],
  },
  {
    id: 'build',
    role: 'build',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-hardhat',
      color: 'safety-yellow',
      badge: 'badge-gear',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'build-blue',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'build-blue',
      'copper',
      'cocoa',
      'plum',
      'navy',
      'silver',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'debug',
    role: 'debug',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-bucket',
      color: 'field-olive',
      badge: 'badge-bug',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'debug-pink',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'debug-pink',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'printer',
    role: 'printer',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'charcoal',
      badge: 'badge-printer',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'orange',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'orange',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'network',
    role: 'network',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'uniform-blue',
      badge: 'badge-wifi',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'network-blue',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'network-blue',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'ai',
    role: 'ai',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beret',
      color: 'ai-pink',
      badge: 'badge-sparkle',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'ai-pink',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'ai-pink',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'general',
    role: 'general',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'ivory',
      badge: 'badge-general',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'ivory',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'ivory',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'test',
    role: 'test',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'lime',
      badge: 'badge-flask',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'lime',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'lime',
      'cocoa',
      'plum',
      'navy',
      'purple',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
    ],
  },
  {
    id: 'deploy',
    role: 'deploy',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'navy',
      badge: 'badge-rocket',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'aqua',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'aqua',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'monitor',
    role: 'monitor',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'monitor-blue',
      badge: 'badge-pulse',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'monitor-blue',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'monitor-blue',
      'silver',
      'sand',
      'mint',
      'coral',
      'copper',
      'teal',
      'pink',
      'blue',
      'amber',
      'purple',
    ],
  },
  {
    id: 'security',
    role: 'security',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'charcoal',
      badge: 'badge-shield',
      badgeColor: 'emblem-ivory',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'charcoal',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'charcoal',
      'silver',
      'sand',
      'mint',
      'coral',
      'copper',
      'teal',
      'pink',
      'blue',
      'amber',
      'purple',
    ],
  },
  {
    id: 'design',
    role: 'design',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beret',
      color: 'charcoal',
      badge: 'badge-pen',
      badgeColor: 'emblem-ivory',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'design-salmon',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'design-salmon',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'data',
    role: 'data',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-beanie',
      color: 'data-cyan',
      badge: 'badge-bars',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'data-cyan',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'data-cyan',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'search',
    role: 'search',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-deerstalker',
      color: 'sand',
      badge: 'badge-search',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'sand',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'sand',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'support',
    role: 'support',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap',
      color: 'support-green',
      badge: 'badge-support',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'support-green',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'support-green',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'docs-editor',
    role: 'docs',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-flatcap',
      color: 'tweed-taupe',
      badge: 'badge-document',
      badgeColor: 'ink',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'ivory',
    allowedHairColors: [
      'ivory',
      'cocoa',
      'plum',
      'silver',
      'teal',
      'copper',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
  },
  {
    id: 'security-officer',
    role: 'security',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-patrol',
      color: 'navy',
      badge: 'badge-shield',
      badgeColor: 'yellow',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'navy',
    allowedHairColors: [
      'navy',
      'cocoa',
      'plum',
      'silver',
      'teal',
      'copper',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
  },
  {
    id: 'deploy-aviator',
    role: 'deploy',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-pilot',
      color: 'aviator-leather',
      badge: 'badge-rocket',
      badgeColor: 'emblem-ivory',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'orange',
    allowedHairColors: [
      'orange',
      'cocoa',
      'plum',
      'silver',
      'teal',
      'copper',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
  },
  {
    id: 'build-red',
    role: 'build',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-hardhat',
      color: 'safety-red',
      badge: 'badge-gear',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'build-blue',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'build-blue',
      'copper',
      'cocoa',
      'plum',
      'navy',
      'silver',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
  {
    id: 'git-backward',
    role: 'git',
    styleId: 'soft-layered-2d',
    hat: {
      type: 'hat-cap-backward',
      color: 'salmon',
      badge: 'badge-git',
      badgeColor: 'white',
    },
    defaultPalette: 'skin',
    defaultHairColor: 'salmon',
    allowedHair: softLayered2dHair,
    allowedInstanceBadges: ['dot', 'check', 'terminal', 'search', 'server'],
    allowedHairColors: [
      'salmon',
      'cocoa',
      'plum',
      'navy',
      'charcoal',
      'silver',
      'copper',
      'teal',
      'pink',
      'mint',
      'blue',
      'amber',
      'coral',
      'purple',
    ],
  },
] as const satisfies readonly BotTemplate[];
